### ISSUE TITLE
To-Dos 1

### ISSUE THREAD

**Issue by melo936** [meetrevision/revision-tool#1]
- [x] Don't rely on `Shell` to apply binary regs tweaks
- [x] #12 
- [ ] Implement an one-click-solution button to revert everything to default
- [x] Implement Power related tweaks (like Hibernation and other power-saving features)
- [x] Improve descriptions 
- [x] Implement updates checker
- [x] #3 
- [ ] Don't rely on PowerShell commands as much as possible

**Comment by couleurm** [comment]
> Don't rely on PowerShell commands as much as possible

If I may ask, why? (curious)

**Comment by dreammjow** [comment]
> If I may ask, why? (curious)

In most situations, there should be some ways to modify something like Memor yCompression other than via PowerShell. Plus PS takes a lot of time load.
