### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by StarNumber12046** [MeetRevision/revision-tool#15]
../Desktop/flutter_windows_3.7.3-stable/flutter/.pub-cache/hosted/pub.dev/fluent_ui-4.1.4/lib/src/controls/inputs/slider.dart(359,8): error GE5CFE876: The method '_CustomTrackShape.paint' has fewer named arguments than those of overridden method 'RoundedRectSliderTrackShape.paint'. [C:\Users\franc\revision-tool\build\windows\flutter\flutter_assemble.vcxproj]
../Desktop/flutter_windows_3.7.3-stable/flutter/.pub-cache/hosted/pub.dev/fluent_ui-4.1.4/lib/src/controls/inputs/slider.dart(359,8): error GE5CFE876: The method '_CustomTrackShape.paint' doesn't have the named parameter 'secondaryOffset' of overridden method 'RoundedRectSliderTrackShape.paint'. [C:\Users\franc\revision-tool\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: la compilazione personalizzata per 'C:\Users\franc\revision-tool\build\windows\CMakeFiles\6486264e745cc9a90b32e596e9c3b494\flutter_windows.dll.rule;C:\Users\franc\revision-tool\build\windows\CMakeFiles\f33b80f605b395530134affcbd45c80e\flutter_assemble.rule;C:\Users\franc\revision-tool\windows\flutter\CMakeLists.txt' � stata terminata. Codice: 1. [C:\Users\franc\revision-tool\build\windows\flutter\flutter_assemble.vcxproj]

**Comment by dreammjow** [comment]
The previous sources weren't compatible with Flutter 3.7 and the latest FluentUI package. However, v1.0.8 should now work correctly.
