### ISSUE TITLE
Feature "Network and GPU monitoring settings" is not working correctly

### ISSUE THREAD

**Issue by finegorko** [meetrevision/revision-tool#26]
When this feature is enabled, only GPU monitoring works, but Network does not. 
![изображение](https://github.com/meetrevision/revision-tool/assets/33998246/1c20b88f-6771-4b03-b2f3-850d094561ea)

I've sorted the results for Network, and I can't see what the network consumes.
![изображение](https://github.com/meetrevision/revision-tool/assets/33998246/aeb55f54-3db1-42ad-8854-b14044c1005e)

**Comment by dreammjow** [comment]
I was able to reproduce the issue on stock Windows several months ago. Here is a current workaround:

![image](https://github.com/meetrevision/revision-tool/assets/50238852/3147e845-7e0c-4395-a6fe-e54ed47a5d1f)

**Comment by finegorko** [comment]
works, thanks!

**Comment by amrly02** [comment]
when i click diagnose it a pop up appears that says your pc doesnt have an app that can open this linke. browser on microsoft store

**Comment by amrly02** [comment]
it didnt work for me. when i press diagnose it opens the "Get Help" windows app then it asks to do network test then asks to restart wifi adapter then nothing happens
