### ISSUE TITLE
Boot time long

### ISSUE THREAD

**Issue by lemmings189** [meetrevision/revision-tool#28]
Hi,
I just updated to the latest win10 version (23.05 using the Upgrade iso) and the booting time is really long, maybe the Superfetch is buggy ?
Previously my pc would boot up in seconds (it has HDD)

Does anyone has the same problem ?
Thanks,

**Comment by lemmings189** [comment]
I deactivated the "Spectre & Meltdown Mitigation" and the boot time decreased significantly, I've an AMD processor so it probably won't be useful.

**Comment by Lordsenpaixd** [comment]
turn on the hibernation
