### ISSUE TITLE
Win Denfender can‘t run real-time protection even I have enabled the switch in Revision Tool.

### ISSUE THREAD

**Issue by Joker5017** [meetrevision/revision-tool#52]
Windows version:
Win11 23H2 22631.2506

Done before:
Enabled the switch in Revision Tool
Uninstalled all anti-virus software

Error:
System red words remind there is still an anti-virus software in control
The enable button can be switched then automatically change back

I wonder how to enable real-time protection in this case.

**Comment by Joker5017** [comment]
problem solved

run CMD (Admin), run following commands in steps :
`winmgmt /salvagerepository
"C:\Program Files\Windows Defender\mpcmdrun.exe" -wdenable
winmgmt /resetrepository`
reboot the system, check the option

**Comment by 27Sasuke** [comment]
Windows version:
Win11 23H2 22631.3527

Windows Security is blank.
It was my default Anti virus. Would be possible to get it back.
