### ISSUE TITLE
Typo in the Performance page

### ISSUE THREAD

**Issue by FalcXD** [meetrevision/revision-tool#58]
I'am nitpicking but there's a grammatical error in this
![image](https://github.com/meetrevision/revision-tool/assets/151380852/11249963-dade-4760-b141-e9becfd964bc)

instead of "in cost of security", its supposed to be "at the cost of security" in the TSX toggle.
Thanks,
Me

**Comment by bytebone** [comment]
make a PR fixing it
https://github.com/meetrevision/revision-tool/blob/94d96bd3da3e549af50cc76d8fbd829eb8349f3f/lib/l10n/intl_en.arb#L51
