### ISSUE TITLE
Disabling File Explorer Tabs breaks File Explorer

### ISSUE THREAD

**Issue by zt3f** [meetrevision/revision-tool#66]
In the Revision Tool, File Explorer Tabs are disabled by default. However, in practice, File Explorer Tabs remain enabled. When attempting to enable and then disable File Explorer Tabs again via the Revision Tool, File Explorer instantly crashes upon attempting to open it after restarting the computer. The issue is resolved by re-enabling File Explorer Tabs via the Revision Tool and restarting the computer. Despite numerous attempts and following advice found through online searches, I could not identify any other workaround for fixing File Explorer.

**Windows Specifications**
- Edition: Windows 11 Pro
- Version: 23H2
- Installed on: ‎January 10, 2024
- OS Build: 22631.3007
- Experience: Windows Feature Experience Pack 1000.22681.1000.0

**Comment by melo936** [comment]
The File Explorer Tabs option relies on Features Overrides, and looks like MS has changed the way it works, therefore only solution would be to completely remove it from the tool.
