### ISSUE TITLE
error flutter: null

### ISSUE THREAD

**Issue by dmrens** [meetrevision/revision-tool#75]

**Comment by dmrens** [comment]
![Ekran Görüntüsü (1)](https://github.com/meetrevision/revision-tool/assets/100730912/10417005-95f1-42d2-a09f-8a27da40f6ea)

**Comment by melo936** [comment]
It's caused by the window manager package that we are using for the title bar.

**Comment by dmrens** [comment]
> It's caused by the window manager package that we are using for the title bar.

So how fix this
