### ISSUE TITLE
[FEATURE] revision-tool-unlocked

### ISSUE THREAD

**Issue by SirDank** [meetrevision/revision-tool#81]
**Is your feature request related to a problem? Please describe.**
I'd love to have this tool on certain systems that do not have the revi-playbook applied and change certain settings. Tbh, it's a clean and simple tool.

**Describe the solution you'd like**
Allow execution of this tool on stock windows ( or allow users to bypass the "Unsupported" error )

**Comment by melo936** [comment]
won't fix, see [this comment](https://github.com/meetrevision/revision-tool/discussions/39#discussioncomment-7016023).
