### ISSUE TITLE
Revision Tool Black Page

### ISSUE THREAD

**Issue by berkkrkc09** [meetrevision/revision-tool#84]
**Describe the bug**
Revision Tool opens to a black/blank page. It seems to be interactable for a short while as I can click on where the close button would be to close the program if I am quick enough. After some time I can't close it with this method.

**To Reproduce**
1. Go to 'start menu'
2. Click on 'revision tool'
3. See black/blank page

**Expected behavior**
Revision Tool opens normally/shows the main page and is interactable.

**Screenshots**
[Screenshot](https://imgur.com/a/a6lfg5t).

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 23H2 22631.3593
 - Playbook Version: ReviOS 23.12
 - Revision Tool Version: Versions from 1.9.0 through 1.10.2

**Additional context**
This is the [output/logs](https://gist.github.com/berkkrkc09/7454106f063ec8512253aaf6b9bcbaf5).
Running on an overclocked Intel Core 2 Duo w/4GB RAM -NO dGPU-
Got the logs from "%temp%\Revision-Tool\Logs". I saw this path in one of the issues.

**Comment by berkkrkc09** [comment]
Just to inform, 1.10.3 didn't change anything about this situation. The issue still persists.

**Comment by melo936** [comment]
It seems like the issue could be related to `window_plus` or a recent Flutter update. It could be your graphics driver too. I'd definitely recommend update/reinstall it.

**Comment by berkkrkc09** [comment]
Since Core 2 Duo has been long discontinued the latest official driver update was in 2012 which is older than mine and the Microsoft update catalog has the exact one I have as latest which I downloaded and installed. Reinstalling didn't help and There isn't a more recent updated driver. Is there a workaround to fix this by any chance?

**Comment by melo936** [comment]
> Since Core 2 Duo has been long discontinued the latest official driver update was in 2012 which is older than mine and the Microsoft update catalog has the exact one I have as latest which I downloaded and installed. Reinstalling didn't help and There isn't a more recent updated driver. Is there a workaround to fix this by any chance?

Try to disable your graphics drivers and run Revision Tool. If it works, once you finish using it, reenable graphics drivers.

**Comment by berkkrkc09** [comment]
It works thanks for letting me know about this workaround.
