### ISSUE TITLE
RevisionTool crashes if the application "LocalSend" is running in the background.

### ISSUE THREAD

**Issue by albryx** [meetrevision/revision-tool#86]
Description:
RevisionTool refuses to launch if "localsend_app.exe" is running, a cmd window will instead show for 0.1 seconds just to close itself. However, if we kill the process "localsend_app.exe", RevisionTool will boot up. 

0. Apply ReviOS playbook "Revi-PB-24.06"
1. Download localsend: https://github.com/localsend/localsend/releases (Latest Version - 1.14.0)
3. Have localsend run in the background.
4. Try to launch RevisionTool.
5. Crash should happen here.

Expected behavior:
Both applications should run fine together.

Desktop:
 - OS: Windows 11 Home 22631.3737
 - Playbook Version: Revi-PB-24.06
 - Revision Tool Version: 1.10.13
 
Additional Context:
As a note, I don't think this happened with previous versions of the tool.

**Comment by melo936** [comment]
Hi, could you try this out? I'm working on refactoring a lot of things, and based on my testing, this issue no longer occurs.

https://github.com/meetrevision/revision-tool/releases/download/1.99.9/RevisionTool-Setup.exe

⚠️ Certain things may not work, like CLI.

**Comment by albryx** [comment]
Hello, I can confirm the version you provided (2.0.0) now works fine with localsend. 
Thank you for the bug fix.
