### ISSUE TITLE
version 1.1.2.0 not working

### ISSUE THREAD

**Issue by Sunil72737** [meetrevision/revision-tool#90]
**Describe the bug**

**To Reproduce**
1. when starting revi tool does not start only showing cmd and closing

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 Pro]
 - Playbook Version: [e.g. ReviOS 23.12]
 - Revision Tool Version: [e.g. 1.1.2.0]

**Additional context**

**Comment by melo936** [comment]
https://github.com/meetrevision/revision-tool/issues/87#issuecomment-2304832054

**Comment by MendokusaiTata** [comment]
this happened to me too.

ReviOS 11 24.06
Windows Update: "You're up to date"
Last checked: Today (25/08/2024), 15:52
Edition: Windows 11 Home Single Language
Version: 23H2
Installed on: ‎07/‎05/‎2022
OS build: 22631.4037
Experience Windows Feature Experience Pack: 1000.22700.1027.0

**Comment by pannox** [comment]
this happened to me too.

**Comment by Cryental** [comment]
If you're getting errors and not fixed with latest version of this tool, you can use mine. It based on the previous flutter but functions are same as last commit.
[revision-tool.zip](https://github.com/user-attachments/files/16930952/revision-tool.zip)

**Comment by pannox** [comment]
thanks ! this work fine

**Comment by xulingfeng931027** [comment]
> 如果您遇到错误并且无法使用此工具的最新版本进行修复，则可以使用我的。它基于之前的 Flutter，但功能与上次提交相同。revision [-tool.zip](https://github.com/user-attachments/files/16930952/revision-tool.zip)

哎哟 这个屌

**Comment by MendokusaiTata** [comment]
> If you're getting errors and not fixed with latest version of this tool, you can use mine. It based on the previous flutter but functions are same as last commit. [revision-tool.zip](https://github.com/user-attachments/files/16930952/revision-tool.zip)

omg thank you so much. your files work perfectly.

**Comment by Pinghigh** [comment]
> If you're getting errors and not fixed with latest version of this tool, you can use mine. It based on the previous flutter but functions are same as last commit. [revision-tool.zip](https://github.com/user-attachments/files/16930952/revision-tool.zip)

thanks, work for me
